//! Golden RNG vectors: tests/golden/rng_vectors.json (generated by
//! tools/reference/rng_reference.py). `Mulberry32Compat` must match the
//! GDScript/Python mulberry32 bit-for-bit, including the rejection-sampling
//! die draws that continue the same stream.

use game_core::rng::{DieRng, Mulberry32Compat};
use serde_json::Value;
use std::path::PathBuf;

fn golden_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/golden")
        .join(name)
}

#[test]
fn rng_golden_vectors_seed_42_0_and_max() {
    let text = std::fs::read_to_string(golden_path("rng_vectors.json"))
        .expect("tests/golden/rng_vectors.json readable");
    let data: Value = serde_json::from_str(&text).unwrap();
    let entries = data.as_object().expect("vector object");
    assert!(entries.len() >= 3, "three seeds expected");
    for (key, entry) in entries {
        let seed: u64 = key
            .trim_start_matches("seed_")
            .parse()
            .unwrap_or_else(|_| panic!("bad vector key {key}"));
        let mut rng = Mulberry32Compat::new(seed);
        // u32 first, then die6 and die4 continue the SAME stream.
        for (i, v) in entry["u32_first_8"]
            .as_array()
            .expect("u32_first_8")
            .iter()
            .enumerate()
        {
            assert_eq!(
                rng.next_u32(),
                v.as_u64().expect("u32 value") as u32,
                "seed {seed}: u32 #{i}"
            );
        }
        for (i, v) in entry["die6_first_8"]
            .as_array()
            .expect("die6_first_8")
            .iter()
            .enumerate()
        {
            assert_eq!(
                rng.next_die(6),
                v.as_u64().expect("die value") as u32,
                "seed {seed}: die6 #{i}"
            );
        }
        for (i, v) in entry["die4_first_4"]
            .as_array()
            .expect("die4_first_4")
            .iter()
            .enumerate()
        {
            assert_eq!(
                rng.next_die(4),
                v.as_u64().expect("die value") as u32,
                "seed {seed}: die4 #{i}"
            );
        }
    }
}
