//! Golden hash vectors: tests/golden/hash_vectors.json (generated by
//! tools/reference/hash_reference.py). Canonical JSON round-trips (parsing a
//! canonical input reproduces it byte-for-byte) and FNV-1a 64 outputs 16
//! uppercase hex characters identical to the GDScript prototype.

use game_core::serialization::{fnv1a64_hex, state_hash, to_canonical};
use serde_json::Value;
use std::path::PathBuf;

fn golden_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/golden")
        .join(name)
}

#[test]
fn hash_golden_vectors() {
    let text = std::fs::read_to_string(golden_path("hash_vectors.json"))
        .expect("tests/golden/hash_vectors.json readable");
    let data: Value = serde_json::from_str(&text).unwrap();
    let inputs = data["inputs"].as_array().expect("inputs array");
    let hashes = data["hashes"].as_array().expect("hashes array");
    assert_eq!(inputs.len(), hashes.len());
    assert!(inputs.len() >= 4, "vectors must cover unicode and nesting");
    for (input, expected) in inputs.iter().zip(hashes.iter()) {
        let canonical = input.as_str().expect("string input").to_string();
        assert_eq!(fnv1a64_hex(&canonical), expected.as_str().expect("hash"));
        // The input is already canonical: parsing + re-canonicalizing must be
        // byte-identical (sorted keys, raw unicode, integer formatting).
        // Non-JSON inputs (the empty string) are used verbatim for hashing.
        if let Ok(parsed) = serde_json::from_str::<Value>(&canonical) {
            assert_eq!(to_canonical(&parsed), canonical, "canonical round-trip");
        }
    }
}

#[test]
fn canonical_matches_godot_examples() {
    // Ship snapshot example from core-api §3: keys sorted recursively.
    let value: Value = serde_json::from_str(
        r#"{"ships": [{"id": "A1_tie_fighter_0", "hp": 4}]}"#,
    )
    .unwrap();
    assert_eq!(
        to_canonical(&value),
        r#"{"ships":[{"hp":4,"id":"A1_tie_fighter_0"}]}"#
    );
    assert_eq!(state_hash(&value), "5B9B593DDB20BE1B");
}
